import { CompanyLogo } from "@ui/logo";
import type { Metadata } from "next";
import Image from "next/image";
import "./auth-layout.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="auth-layout">
      <div className="auth-layout__logo">
        <CompanyLogo />
      </div>

      <section className="auth-layout__branding">
        <Image src="/auth.svg" alt="Branding" width={600} height={338} />
      </section>

      <section className="auth-layout__content">{children}</section>
    </main>
  );
}
