import "../styles/globals.scss";

import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";

import { RootProvider } from "./Provider";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${workSans.variable}`}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
